// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package grpcservice

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GPRCServiceClient is the client API for GPRCService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GPRCServiceClient interface {
	Generate(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type gPRCServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGPRCServiceClient(cc grpc.ClientConnInterface) GPRCServiceClient {
	return &gPRCServiceClient{cc}
}

func (c *gPRCServiceClient) Generate(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/grpcservice.GPRCService/Generate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GPRCServiceServer is the server API for GPRCService service.
// All implementations must embed UnimplementedGPRCServiceServer
// for forward compatibility
type GPRCServiceServer interface {
	Generate(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedGPRCServiceServer()
}

// UnimplementedGPRCServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGPRCServiceServer struct {
}

func (UnimplementedGPRCServiceServer) Generate(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Generate not implemented")
}
func (UnimplementedGPRCServiceServer) mustEmbedUnimplementedGPRCServiceServer() {}

// UnsafeGPRCServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GPRCServiceServer will
// result in compilation errors.
type UnsafeGPRCServiceServer interface {
	mustEmbedUnimplementedGPRCServiceServer()
}

func RegisterGPRCServiceServer(s grpc.ServiceRegistrar, srv GPRCServiceServer) {
	s.RegisterService(&GPRCService_ServiceDesc, srv)
}

func _GPRCService_Generate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GPRCServiceServer).Generate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcservice.GPRCService/Generate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GPRCServiceServer).Generate(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// GPRCService_ServiceDesc is the grpc.ServiceDesc for GPRCService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GPRCService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpcservice.GPRCService",
	HandlerType: (*GPRCServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Generate",
			Handler:    _GPRCService_Generate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpcservice.proto",
}
